Add the required files
ChaabaneAnas/Hello-Microverse-Project- pull request #1
Opened 2022-05-24 14:23 UTC by ChaabaneAnas

Add a .gitignore file.
Set up linters
Add a descriptive README file
Add 3 files (each one in a separate commit):
A .html file that includes a header with the text "Hello Microverse!"
A .css file that includes one class with styles for your header 
A test.md file ignored

2022-05-24 14:43 UTC, Lucas-Masaba requested changes
# Hello @ChaabaneAnas  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 

You have submitted a project that does not have stylelint checks passing as seen in the image below. Please make sure you have everything as a ✔️ and not a ❌ 
![image](https://user-images.githubusercontent.com/45460192/170063346-5111f368-c028-49eb-b56a-702e3d13fa42.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-24 15:13 UTC, ChaabaneAnas commented
Hi @Lucas-Masaba,
so ive managed to fix stylelint 3 errors ...
one of them had to be fixed by adding the newline elem ( /n)
but now I'm receiving another error Csssyntaxerorr instead

2022-05-24 15:20 UTC, Lucas-Masaba commented
Hello @ChaabaneAnas, let me look into it briefly

2022-05-24 15:25 UTC, ChaabaneAnas commented
ok thx for being there <3

Le mar. 24 mai 2022 à 16:21, Khusiima Luke Masaba ***@***.***>
a écrit :

> Hello @ChaabaneAnas <https://github.com/ChaabaneAnas>, let me look into
> it briefly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ChaabaneAnas/Hello-Microverse-Project-/pull/1#issuecomment-1136067107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXX3YFLTWMOMTJIQJQUVP43VLTXWJANCNFSM5WZYJ5BQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-24 15:49 UTC, Lucas-Masaba commented
No worries

2022-05-24 15:59 UTC, ChaabaneAnas commented
this time-draining  im still left with more than 4 hours to go is it a bug or something?

2022-05-24 16:24 UTC, ChaabaneAnas commented
Hello again @Lucas-Masaba 
Finally it worked could review it pls  ?

2022-05-24 16:44 UTC, youmari commented on README.md
> + ...
- [ ] it would be better if you use the [readme template ](https://github.com/microverseinc/readme-template)provided by microverse and add your info to it so that your Readme will be professional and useful 
- and don't forget a description of your project, your social media account and how can use your project locally

2022-05-25 09:17 UTC, topeogunleye approved these changes
### Hi @ChaabaneAnas, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 09:45 UTC, merged